---
all:
  children:
    dns_servers:
      hosts:
        dns01:
          ansible_host: 192.168.1.10
          ansible_user: votre_utilisateur
          # ansible_become_password: !vault |
          #   $ANSIBLE_VAULT;1.1;AES256
          #   ...
